### ISSUE TITLE
`${datetime}` not replaced

### ISSUE THREAD

**Issue by nmrugg** [kaizhu256/node-istanbul-lite#2]
Whenever you generate a report, there is always the text `Generated by utility2 at ${datetime}`. The `${datetime}` is not being replaced.

**Comment by kaizhu256** [comment]
thx for reporting.  fixed in commit 1dad23d, and updated [online demo](https://kaizhu256.github.io/node-istanbul-lite/build..beta..travis-ci.com/app/) with fix as well.

![image](https://user-images.githubusercontent.com/280571/145672278-0cee79b2-3a34-448e-ac78-409455ce2aac.png)

**Comment by nmrugg** [comment]
Works. Thanks.
